# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function to convolve two vectors using nested for loop
#'
#' @name convolve_cpp
#' @param a A vector
#' @param b A vector
#' @return A vector containing the convolution of a and b
#'
#' @details This is an internal function
#'       Same result as, in R:
#'       convolve(a, b, conj=TRUE, type="open")
NULL

#' @author Dirk Eddelbuettel
NULL

convolve_cpp <- function(a, b) {
    .Call(`_dependlab_convolve_cpp`, a, b)
}

#' This function convolves a stimulus vector with the double-gamma hrf
#'
#' @name convolve_double_gamma
#' @param x A vector of volume numbers used to evaluate the function at each value
#' @param a1 The a1 parameter of the double gamma
#' @param a2 The a2 parameter of the double gamma
#' @param b1 The b1 parameter of the double gamma
#' @param b2 The b2 parameter of the double gamma
#' @param cc The cc parameter of the double gamma
#' @return A vector of the double-gamma HRF at each value of \code{x}
#'
#' @details This is an internal function that is used by convolve_hrf
#' @author Michael Hallquist
NULL

convolve_double_gamma <- function(stimulus, a1 = 6.0, a2 = 12.0, b1 = 0.9, b2 = 0.9, cc = 0.35) {
    .Call(`_dependlab_convolve_double_gamma`, stimulus, a1, a2, b1, b2, cc)
}

#' This function creates K shifts of a neural events vector according to the kernel length, K.
#'
#' @name generate_feature
#' @param encoding The neural events vector (same length as BOLD time series)
#' @param K The length of the kernel
#' @return A matrix of length(encoding) rows and K columns, where each column contains a successively
#'    lagged copy of the encoding vector
#'
#' @details This is an internal function that is used inside a while loop by deconvolve_nlreg.
#'   Profiling of the algorithm revealed that this is the primary bottleneck, so I ported it to
#'   an Rcpp function
#' @author Michael Hallquist
NULL

generate_feature <- function(encoding, K) {
    .Call(`_dependlab_generate_feature`, encoding, K)
}

#' This function creates K shifts of a neural events vector according to the kernel length, K.
#'
#' @name generate_feature_armadillo
#' @param encoding The neural events vector (same length as BOLD time series)
#' @param K The length of the kernel
#' @return A matrix of length(encoding) rows and K columns, where each column contains a successively
#'    lagged copy of the encoding vector
#'
#' @details This is an internal function that is used inside a while loop by deconvolve_nlreg.
#'   Profiling of the algorithm revealed that this is the primary bottleneck, so I ported it to
#'   an Rcpp function
#' @author Michael Hallquist
NULL

generate_feature_armadillo <- function(encoding, K) {
    .Call(`_dependlab_generate_feature_armadillo`, encoding, K)
}

