# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This function creates K shifts of a neural events vector according to the kernel length, K.
#'
#' @name generate_feature
#' @param encoding The neural events vector (same length as BOLD time series)
#' @param K The length of the kernel
#' @return A matrix of length(encoding) rows and K columns, where each column contains a successively
#'    lagged copy of the encoding vector
#'
#' @details This is an internal function that is used inside a while loop by deconvolve_nlreg.
#'   Profiling of the algorithm revealed that this is the primary bottleneck, so I ported it to
#'   an Rcpp function
#' @author Michael Hallquist
NULL

generate_feature <- function(encoding, K) {
    .Call(`_dependlab_generate_feature`, encoding, K)
}

#' This function creates K shifts of a neural events vector according to the kernel length, K.
#'
#' @name generate_feature_armadillo
#' @param encoding The neural events vector (same length as BOLD time series)
#' @param K The length of the kernel
#' @return A matrix of length(encoding) rows and K columns, where each column contains a successively
#'    lagged copy of the encoding vector
#'
#' @details This is an internal function that is used inside a while loop by deconvolve_nlreg.
#'   Profiling of the algorithm revealed that this is the primary bottleneck, so I ported it to
#'   an Rcpp function
#' @author Michael Hallquist
NULL

generate_feature_armadillo <- function(encoding, K) {
    .Call(`_dependlab_generate_feature_armadillo`, encoding, K)
}

